### ISSUE TITLE
Authentication problem cannot create a new admin

### ISSUE THREAD

**Issue by MadHatter122312** [IgorDraskovic/RestarauntCRUDAppV2#1]
I have locked myself out of food because I cannot create a new admin.  I can go into the log_in view and enter a name and password but that obviously does not work since I never created an admin.  When I try to go to admins/new I get this error: 

```
def find(*args)
  find_all(*args).first || raise(MissingTemplate.new(self, *args))
end

def find_all(path, prefixes = [], *args)
```

**Comment by rapala61** [comment]
You need to make a contributor for this new repo

**Comment by MadHatter122312** [comment]
Just did thanks!
