### ISSUE TITLE
Calculating Gratuity

### ISSUE THREAD

**Issue by MadHatter122312** [IgorDraskovic/RestarauntCRUDAppV2#4]
I am not sure if I have to write a adding total method into food.rb or order.rb...I am just trying to show the total for each suggested gratuity by multiplying by .15, .20 etc.  Do I even require a method for this....?

**Comment by rapala61** [comment]
The simplest way would be to calculate it at the view level. The long way is to create a second method that returns a hash of possible discounts and their values based on the total (You should have the "total" feature working for this already), then render the "gratuity" section based on this returned hash.

**Comment by rapala61** [comment]
In person
