### ISSUE TITLE
Project Two Feedback

### ISSUE THREAD

**Issue by ajhofferber** [IgorDraskovic/RestarauntCRUDAppV2#5]
Hey Igor,

Nice work on your project! I like how you chose to go with a simple, clean aesthetic... Makes a lot of sense for a POS system! 

I didn't receive admin log-in credentials from you this morning, so I am not sure what is different upon logging in. I do know that I am unable to access the menu to change it in the admin panel without logging in, so that is good! Also, it looks like you were able to work in some testing, which is wonderful to see! 

Your markdown is really thorough and includes important information, so kudos for that! Overall I think your finished product on this is very nice.

Score: 2 - Meets expectations, great!

**Comment by MadHatter122312** [comment]
Wow! I did it!?

Amazing.  Thanks Ash

As for the long-in info nothing is seeded in the database, you can simply cate an admin account, but if you don’t and try to edit menu items you will be redirected back because it requires authentication.  You can see it in my controller…coo?

Igor
